version: 2
project_name: line-cli

builds:
  - main: ./cmd/line
    binary: line
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/salmonumbrella/line-official-cli/internal/cmd.version={{.Version}}
      - -X github.com/salmonumbrella/line-official-cli/internal/cmd.commit={{.Commit}}
      - -X github.com/salmonumbrella/line-official-cli/internal/cmd.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
